version: 2.1
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --2
      - restore_cache:
          key: composer-v1-{{ checksum "./src/composer.lock" }}
      - run:
          command: composer install -n --prefer-dist
          working_directory: src
      - save_cache:
          key: composer-v1-{{ checksum "./src/composer.lock" }}
          paths:
            - vendor
      - run:
          command: npm ci
          working_directory: src
      - run:
          command: npm run dev
          working_directory: src
      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: src
