version: 2.1
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/php:7.4-node-browsers
      - image: circleci/mysql:8.0
        environment:
          - MYSQL_DATABASE: laravel

    environment:
      - DB_HOST: 127.0.0.1
    steps:
      - checkout
      - run:
          name: Install depencies
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B
            sudo apt-get update --allow-releaseinfo-change
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo composer self-update --2
      - restore_cache:
          key: composer-v1-{{ checksum "./src/composer.lock" }}
      - run:
          command: composer install -n --prefer-dist
          working_directory: src
      - save_cache:
          key: composer-v1-{{ checksum "./src/composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "./src/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
          working_directory: src
      - save_cache:
          key: npm-v1-{{ checksum "./src/package-lock.json" }}
          paths:
            - node_modules
      - run:
          command: npm run dev
          working_directory: src
      - run:
          name: php test
          command: |
            mkdir tests/Unit
            vendor/bin/phpunit
          working_directory: src
